"""Editorial content for Move In Thailand. Facts and sources are kept together."""

CHECKED = "8 October 2026"
SOURCES = {
    "dtv": ("Royal Thai Embassy · Destination Thailand Visa", "https://london.thaiembassy.org/en/page/destination-thailand-visa"),
    "dtv_detail": ("Royal Thai Embassy Budapest · DTV requirements", "https://budapest.thaiembassy.org/en/publicservice/destination-thailand-visa-dtv"),
    "ltr": ("Thailand Board of Investment · LTR programme", "https://ltr.boi.go.th/"),
    "privilege": ("Thailand Privilege · Official programme", "https://www.thailandprivilege.co.th/home"),
    "retirement": ("Royal Thai Embassy · Retirement visa routes", "https://london.thaiembassy.org/en/page/retirement-visa"),
    "marriage": ("Royal Thai Embassy · Spouse and family visas", "https://london.thaiembassy.org/en/page/spouse-and-family-visa"),
    "business": ("Royal Thai Embassy · Business visa", "https://london.thaiembassy.org/en/page/business-visa"),
    "evisa": ("Thai Ministry of Foreign Affairs · e-Visa", "https://www.thaievisa.go.th/"),
    "condo": ("Department of Lands · Condominium Act, English translation", "https://www.dol.go.th/legal/Documents/Consultation%20and%20draft%20legislation%20Group/CONDOMINIUM%2BACT%2C%2BB.E.%2B2522%2B%281979%29.pdf"),
    "dbd": ("Department of Business Development · Foreign business guidance", "https://www.dbd.go.th/data-storage/attachment/c19e85b2683b02564c62fbe2.pdf"),
    "boi": ("Thailand Board of Investment", "https://www.boi.go.th/"),
    "immigration": ("Thai Immigration Bureau", "https://www.immigration.go.th/"),
}

VISAS = [
    dict(slug="dtv", name="Destination Thailand Visa", short="DTV", label="Remote work & eligible activities", icon="laptop", badge="Explore from abroad",
         summary="For overseas remote work, eligible Thai activities, and qualifying dependants. Understand the purpose and evidence before applying.",
         title="Work remotely. Make room for a different rhythm.",
         intro="If your work travels with you, the Destination Thailand Visa may be a route to explore. Start with your purpose, your financial evidence, and the Thai embassy responsible for your application.",
         facts=[("5 years", "Visa validity"), ("Up to 180 days", "Per entry"), ("THB 500,000", "Financial evidence threshold")],
         sections=[("Who should explore the DTV?", "Overseas remote workers, freelancers and people joining eligible activities such as Muay Thai or Thai cooking can explore this route. Qualifying spouses and dependent children may also have a route. A hobby, a course booking or a remote job title alone does not establish eligibility."),
                   ("Put the evidence before the application", "Bring together proof of your current location, your finances and your reason for visiting. Work contracts, a portfolio or activity documentation may be relevant. The embassy handling your application sets its document requirements and may ask for more evidence."),
                   ("Make the stay match the purpose", "Five-year visa validity is different from permission to stay for five years continuously. The DTV does not provide permission to work for Thai companies or freelance for Thai clients. Tell us how you actually work so your shortlist reflects your circumstances."),
                   ("A practical next step", "We can organise a document checklist, identify questions for your embassy and coordinate a rental search around your intended stay. Ask for a written service quote before authorising application support.")],
         checklist=["Passport and current residence", "Remote work or activity evidence", "Financial evidence", "Family documents, if applicable"],
         faqs=[("Does the DTV let me work for a Thai employer?", "It is not a Thai employment route. Explore the appropriate employment visa and work permission if you intend to work for a Thai company."), ("Is the financial threshold a fee?", "No. Evidence of funds is different from an application fee. Confirm acceptable evidence and the official fee with your responsible embassy.")],
         sources=["dtv", "dtv_detail"]),
    dict(slug="ltr", name="Long-Term Resident Visa", short="LTR", label="Professionals, pensioners & investors", icon="compass", badge="BOI qualification review",
         summary="An option for qualifying professionals, wealthy pensioners and global citizens. Start with a review of the relevant BOI category.",
         title="A longer horizon. A carefully checked route.",
         intro="The Long-Term Resident programme has distinct categories for different circumstances. A good LTR plan starts with the category you can substantiate, rather than the benefits you hope to receive.",
         facts=[("Up to 10 years", "Subject to continuing qualifications"), ("4 categories", "Principal applicant routes"), ("BOI", "Qualification endorsement")],
         sections=[("Find the category that fits your evidence", "The programme covers wealthy global citizens, wealthy pensioners, work-from-Thailand professionals and highly skilled professionals. Dependants have separate requirements. The evidence needed changes by category; it is not a single checklist for everyone."),
                   ("Treat continuing conditions as part of the plan", "The BOI describes an initial five-year permission with a further five years available when qualifications are maintained. Income, employment, insurance and investments may matter for your category. Build a calendar around the conditions you must continue to meet."),
                   ("Keep tax and employment advice specific", "Advertised programme benefits do not replace a review of your tax circumstances or your work activity. Ask a qualified adviser to check how the programme would apply to you before changing your employment or moving substantial funds."),
                   ("What we help coordinate", "A category comparison, an evidence inventory, questions for the BOI and the practical housing and arrival steps that follow. Qualification endorsement and immigration decisions remain with the authorities.")],
         checklist=["Proposed LTR category", "Income, assets or employment evidence", "Insurance or accepted alternative", "Dependant information"],
         faqs=[("Does everyone qualify for a ten-year stay?", "No. Both the category requirements and continuing conditions matter. The programme describes an initial five-year permission and an extension subject to maintaining qualifications."), ("Can you guarantee BOI endorsement?", "No. We help organise the process and evidence; the BOI and immigration authorities decide the application.")],
         sources=["ltr"]),
    dict(slug="thailand-privilege", name="Thailand Privilege", short="Privilege", label="Longer stays through membership", icon="spark", badge="Formerly Thai Elite",
         summary="Compare the official membership programme, formerly Thai Elite, with other routes before committing to a membership fee.",
         title="More time in Thailand. Know what you are buying.",
         intro="Thailand Privilege is a membership programme with long-term visa benefits. It may suit people prioritising convenience, but the membership cost, permitted activities and family arrangements deserve a clear comparison.",
         facts=[("Membership", "An official programme"), ("Several tiers", "Compare current benefits"), ("No work permission", "From membership alone")],
         sections=[("Compare the whole membership", "Look at the current official price, membership duration, included services and family arrangements together. Choose a tier for benefits you expect to use. Promotional pricing and membership offers can change, so use the current official quotation."),
                   ("Separate residence from work", "A membership with visa benefits is not an unrestricted right to work or study in Thailand. If you intend to run a business, take local employment or enrol in formal study, explain that intention before choosing a route."),
                   ("Separate programme fees from our fees", "Ask for the programme's official membership quotation and a separate description of any coordination service. Your written quote should say who receives each payment, what is included and which cancellation terms apply."),
                   ("Plan the home alongside the stay", "Explore neighbourhoods, a first rental and the practical arrangements for your family. An initial rental can give you time to understand daily life before deciding whether to buy.")],
         checklist=["Current official tier comparison", "Planned activities in Thailand", "Family membership arrangements", "Written fee and cancellation terms"],
         faqs=[("Is Thailand Privilege the same as Thai Elite?", "Thailand Privilege is the current programme name. Many people still search for it as the Thai Elite visa."), ("Are you an officially appointed programme agent?", "Ask us to confirm any appointment status before relying on it. Our website does not claim official agent accreditation.")],
         sources=["privilege"]),
    dict(slug="retirement", name="Thailand Retirement Visas", short="Retirement", label="A new chapter at 50 and beyond", icon="sun", badge="Compare O, O-A & O-X",
         summary="Compare retirement routes, financial evidence and ongoing obligations with a practical plan for everyday life.",
         title="More life in your days. Less uncertainty in your move.",
         intro="Retiring in Thailand is a decision about your daily life as much as your visa. Start with the appropriate retirement route, then build a plan for housing, healthcare and the obligations that continue after arrival.",
         facts=[("50+", "Age threshold for retirement routes"), ("Different routes", "O, O-A and O-X"), ("Ongoing care", "Renewals and reporting")],
         sections=[("A retirement visa is not one single product", "Non-Immigrant O, O-A and O-X routes differ in their entry arrangements and conditions. The right comparison depends on where you apply, your nationality and residence, and the length of stay you want. Do not transfer another person's checklist to your own application."),
                   ("Put healthcare in the first conversation", "Insurance requirements can vary by route. Consider your cover, exclusions, ongoing costs and access to the care you actually need. Verify visa-specific insurance requirements before purchasing a policy."),
                   ("Rent first, learn the neighbourhood", "Spend time around the supermarkets, clinics, transport and places you will use each week. A home that photographs well may not suit your routine. We help connect the housing search to your practical priorities."),
                   ("Know what happens next year", "Plan for renewals, address matters, reporting and travel arrangements that apply to your status. A clear calendar is more valuable than discovering an obligation when a deadline is close.")],
         checklist=["Nationality and place of application", "Retirement route comparison", "Financial and insurance evidence", "Housing and healthcare priorities"],
         faqs=[("Does being over 50 make me eligible automatically?", "No. Age is only one condition. The relevant route also has documentary and financial requirements."), ("Can you help after the initial visa?", "Ask about Residency Care for the reminders and coordination appropriate to your status. Each service and fee is agreed in writing.")],
         sources=["retirement", "immigration"]),
    dict(slug="business", name="Thailand Business Visa", short="Business", label="Business visits & employment", icon="briefcase", badge="Visa and work permission together",
         summary="Understand Non-Immigrant B, work permission and company documentation before planning a business or employment move.",
         title="Build your next opportunity on the right foundations.",
         intro="A business visit, local employment and operating your own company are different situations. Tell us what you plan to do so we can help coordinate the visa, company and work-permission questions in the right order.",
         facts=[("Non-Immigrant B", "A business and employment route"), ("Activity matters", "Match evidence to your purpose"), ("Work permission", "Check separately")],
         sections=[("Start with the activity", "Meeting suppliers, accepting a Thai job and actively running a company call for different preparation. Write down who you will work for, where your customers are and what you will do in Thailand. Those details are more useful than a generic business-visa label."),
                   ("Prepare company and employer evidence", "The responsible embassy may require invitation letters, registration documents and employment-related approvals. Confirm its current list and who in the company will supply each document."),
                   ("Company ownership is a separate review", "A visa does not make a proposed business structure lawful. Ownership restrictions, licences, work permission and tax registration need their own review. Never rely on a nominee arrangement to bypass restrictions."),
                   ("Coordinate the commercial and personal move", "Agree the legal review and evidence plan first. Then connect the expected timeline with a first rental, your family's arrival and the everyday arrangements you will need.")],
         checklist=["Business activity and role", "Employer or company documents", "Work-permission questions", "Family and arrival timeline"],
         faqs=[("Does a business visa itself authorise every kind of work?", "No. Visa status and permission to work must be checked for your activity."), ("Can you help register a company?", "We can coordinate a company setup review. The structure and any licences must be checked for your actual activity before registration.")],
         sources=["business", "dbd"]),
    dict(slug="marriage", name="Thailand Marriage & Family Visa", short="Marriage & family", label="Joining a Thai spouse or family", icon="heart", badge="A family plan, together",
         summary="Make a clear family document plan for a Thai spouse or other qualifying family relationship.",
         title="A home together. A clearer path to getting there.",
         intro="When your move is about family, the paperwork can feel personal. We help you organise the questions and documents for the family route that matches your relationship and circumstances.",
         facts=[("Non-Immigrant O", "A route to explore"), ("Relationship evidence", "Prepare the documents"), ("Extension review", "Conditions continue")],
         sections=[("Match the route to the relationship", "A Thai spouse, a Thai child and a dependant of a foreign resident are different situations. Explain the relationship, your current residence and the main applicant's status before choosing a checklist."),
                   ("Check how documents will be accepted", "Marriage and birth certificates may need translation, certification or legalisation depending on the issuing country and application. Confirm what is needed before paying for document services."),
                   ("Think beyond the first arrival", "The initial visa and an extension of stay are separate stages. Understand the evidence and ongoing arrangements you may need for the next stage. Decisions and extension permissions remain with immigration authorities."),
                   ("Plan around your family", "A first home, school choices, healthcare and travel timing should support the family rather than create more pressure. We help turn those decisions into an ordered plan.")],
         checklist=["Relationship and civil documents", "Main applicant's status", "Translation or legalisation questions", "Family housing and school priorities"],
         faqs=[("Does marriage guarantee permission to stay?", "No. You still need the appropriate application and supporting evidence, and the authorities decide permission."), ("Will my family all use the same application?", "Not necessarily. Each person's nationality, relationship and circumstances should be checked.")],
         sources=["marriage", "immigration"]),
    dict(slug="education", name="Thailand Education & Activity Visas", short="Study & activities", label="Language, Muay Thai & study", icon="book", badge="Purpose comes first",
         summary="Compare genuine study and eligible activity routes with the school or provider before making a payment.",
         title="Come for the experience. Choose a route that fits it.",
         intro="A language course, a Muay Thai programme and formal education are not interchangeable visa purposes. Start with what you genuinely want to learn and verify the appropriate route with the institution and embassy.",
         facts=[("Study purpose", "Choose a genuine programme"), ("Provider evidence", "Verify supporting documents"), ("Route review", "ED or eligible DTV activity")],
         sections=[("Choose the programme before the paperwork", "Understand the curriculum, attendance, duration and provider's credentials. Ask what documentation it can issue and what happens if your visa application is refused. A course purchase is not a guarantee of immigration permission."),
                   ("Compare ED and activity-based DTV carefully", "Formal study may require an education route. Eligible activities may be considered for DTV, subject to the embassy's requirements. Children whose primary purpose is school attendance should have the appropriate education route reviewed."),
                   ("Budget for your real day-to-day life", "Include tuition, rent, transport to class, insurance and initial setup. Choose a home that fits the course schedule and the length of permission you are seeking."),
                   ("Your next step", "Bring the programme details and intended dates to a route review. We help organise the provider and embassy questions before you commit to travel or accommodation.")],
         checklist=["Programme and provider details", "Course dates and attendance", "Provider's refund terms", "Embassy-specific document list"],
         faqs=[("Will any Muay Thai course qualify for DTV?", "No. Eligibility and the provider evidence must meet the responsible embassy's current requirements."), ("Can I choose a school purely to obtain a visa?", "Choose a programme you genuinely intend to attend. Your application should accurately represent your purpose.")],
         sources=["dtv_detail", "evisa"]),
]

FAQ = [
    ("I’m still researching. Is it too early to talk?", "That is a good time to start. You do not need a selected visa or a property shortlist. A first conversation helps put your options, timeline and next decisions in order."),
    ("Can you help with both my visa and my home?", "Yes. We coordinate the visa questions and your housing search together, so the lease, location and arrival timeline make sense for the same move."),
    ("How will I know what I’m paying for?", "Before paid work starts, ask for a written scope and fee breakdown. Official fees, our service fee and any third-party costs should appear separately. Changes need a revised quote."),
    ("Can you guarantee a visa approval?", "No. The embassy, BOI or immigration authority makes the decision. Our role is to explain the route, organise the evidence and help you understand what remains uncertain."),
    ("Do I need to buy property to move to Thailand?", "Buying a home is not the starting point for every move. Many people begin with a rental. Visa permission and property ownership are separate questions that deserve separate checks."),
    ("What happens after I arrive?", "We can coordinate the next steps for housing and settling in, then discuss Residency Care for the renewals and reporting relevant to your status. The scope is agreed around what you need."),
]

SERVICES = [
    dict(title="Your visa, understood.", label="01 / VISA DESK", icon="passport", href="visas/", text="DTV, LTR, Thailand Privilege, retirement, business and family. Know your route and your document list before you spend a baht.", link="Explore visa routes"),
    dict(title="A place to feel at home.", label="02 / HOMES", icon="home", href="homes/", text="Pattaya rentals, condo buying and the right neighbourhood. A home that fits your life and your move date, without the legwork.", link="Find your home"),
    dict(title="Room for your ambition.", label="03 / BUSINESS & INVEST", icon="briefcase", href="business/", text="Company setup, BOI questions and property due diligence. See the structure and the full cost before you commit.", link="Explore the possibilities"),
    dict(title="Support beyond arrival.", label="04 / RESIDENCY CARE", icon="heart", href="residency-care/", text="Your renewals and reports on one calendar, so the deadlines stop living in your head. Practical help as life here takes shape.", link="See ongoing support"),
]


def editorial(slug, title, eyebrow, heading, intro, sections, *, image="home", sources=None, cards=None, faqs=None, checklist=None):
    return dict(slug=slug, title=title, eyebrow=eyebrow, heading=heading, intro=intro, sections=sections, image=image, sources=sources or [], cards=cards or [], faqs=faqs or [], checklist=checklist or [], template="editorial", description=intro[:155])


PAGES = [
    dict(slug="", title="Move to Thailand | Visas, Homes & Relocation | Move In Thailand", description="Plan your move to Thailand with one local desk for visas, homes, business and residency care. Explore visa routes, estimate your budget and request a clear move plan.", template="home"),
    dict(slug="visas", title="Thailand Visa Options | DTV, LTR, Privilege & Retirement", description="Compare Thailand visa routes for remote work, retirement, business and family. Find a practical shortlist and check the official sources.", template="visas"),
    dict(slug="tools", title="Thailand Relocation Tools | Visa Finder & Budget Calculator", description="Use our Thailand Visa Finder, editable living-cost calculator and property ownership checklist to plan your next step.", template="tools"),
    dict(slug="tools/visa-finder", title="Thailand Visa Finder | Explore Routes for Your Circumstances", description="Answer a few questions to explore Thailand visa routes. Get a starting shortlist, document questions and official sources, without sharing contact details.", template="finder"),
    dict(slug="tools/cost-calculator", title="Thailand Cost of Living Calculator | Plan Your Monthly Budget", description="Build an editable Thailand living budget for rent, food, transport and healthcare. Estimate monthly and arrival costs with assumptions you control.", template="calculator"),
    dict(slug="tools/ownership-checker", title="Thailand Property Ownership Checklist for Foreign Buyers", description="Explore the checks for a Thailand condominium, lease or company purchase before committing funds. See official sources and prepare questions for a lawyer.", template="ownership"),
    dict(slug="contact", title="Plan Your Move to Thailand | Request a Free 15-Minute Call", description="Tell us your timeline and priorities. Request a free 15-minute conversation about moving to Thailand, visas, a home or a business.", template="contact"),
    dict(slug="fees", title="Thailand Relocation Fees | Understand the Full Cost", description="Understand official fees, service fees and third-party costs before committing to Thailand visa or relocation support. Request a written scope and quote.", template="fees"),
    editorial("homes", "Homes in Thailand | Pattaya Rentals & Condo Buying", "YOUR HOME IN THAILAND", "Find a home for the life you want to live.", "The right home is more than a view. It is the neighbourhood, the commute, the budget and how comfortably your first months come together.",
              [("Start with your everyday life", "Tell us how you want a normal Tuesday to feel: a quiet morning, a short trip to school, a walk to the beach or a reliable workspace. Those details make a better shortlist than choosing by photographs alone."), ("Connect the home to the move", "Coordinate your rental dates with your application and arrival plans. Ask about deposits, utilities, building rules and the paperwork you will need before signing."), ("Visit before you commit", "A viewing helps you understand noise, transport, maintenance and how the property actually feels. If buying, arrange independent legal checks on title, ownership conditions and payment terms before a deposit.")],
              cards=[("Rent in Pattaya", "A flexible first chapter, with a shortlist around your routine.", "homes/rent-in-pattaya/"), ("Buy a condo in Thailand", "Understand title, ownership conditions and transaction costs.", "homes/buy-condo-thailand/"), ("Life in Pattaya", "Compare areas before deciding where you want to settle.", "living/pattaya/")]),
    editorial("homes/rent-in-pattaya", "Rent in Pattaya | Long-Term Homes for Your Thailand Move", "RENT FIRST, SETTLE WELL", "Make your first home a good beginning.", "A first rental gives you room to learn the city before making a bigger decision. Build a Pattaya rental shortlist around your actual dates, budget and daily needs.",
              [("The details that improve your shortlist", "Set an all-in monthly budget and explain who is moving, whether you have pets and the places you need to reach. Ask about internet, furnishings, accessibility and lease length."), ("Read the lease before paying", "Confirm the landlord's identity, deposit terms, utility rates, cancellation conditions and check-in inventory. Ask who handles address reporting and what evidence the accommodation can provide."), ("Browse real homes with our property partner", "Pattaya Home Pro carries property listings and viewing enquiries. Availability and asking prices change; confirm the current terms for the exact home before arranging payment.")],
              checklist=["Arrival date and preferred lease length", "All-in monthly budget", "Area, transport and accessibility", "Deposit and utility terms"]),
    editorial("homes/buy-condo-thailand", "Buying a Condo in Thailand as a Foreigner | Practical Guide", "A CAREFUL PROPERTY PURCHASE", "Love the home. Understand the ownership.", "Before buying a condominium in Thailand, have the title, foreign ownership conditions and transaction reviewed for the specific unit.",
              [("Check the ownership conditions", "Foreign condominium ownership is subject to eligibility and the building's foreign ownership limit. The Condominium Act sets that limit at 49% of the total unit area. Ask for current confirmation for the building and independent review of the unit."), ("Prepare the payment trail", "Ask your lawyer and receiving bank what evidence is required for your funding and transfer. Do this before sending money so the records support the intended registration."), ("Look beyond the asking price", "Review transfer costs, common-area charges, maintenance, a sinking fund if applicable and ongoing management. Forecast costs separately from any hoped-for rental income."), ("Keep residence and ownership separate", "A property purchase does not automatically grant a visa or permission to stay. Plan your residence route independently of the transaction.")],
              sources=["condo"], checklist=["Title and seller authority", "Current foreign quota confirmation", "Funding and transfer evidence", "Contract, fees and ongoing costs"]),
    editorial("business", "Start a Business in Thailand | Company Setup & BOI Review", "YOUR BUSINESS IN THAILAND", "A good opportunity deserves a sound foundation.", "Whether you are starting a company or buying a business, begin with the activity, the ownership rules and the practical costs of operating it.",
              [("Describe the business, not just the company", "Explain the customers, the services, where the work happens and what you will do personally. Licensing and ownership questions depend on the activity; a registration alone is not the whole answer."), ("Get the structure reviewed first", "Have a qualified Thai lawyer assess foreign ownership, licences, work permission and your contracts. Nominee shareholders should never be used to bypass the rules."), ("Read the numbers before a business purchase", "Check accounts, leases, licences, staff obligations and any debts or disputes. Independent commercial and legal due diligence help you understand what you would actually acquire.")],
              sources=["dbd", "boi"], cards=[("Company setup", "An ordered checklist from activity review to operations.", "business/company-setup/"), ("BOI possibilities", "Explore whether your proposed activity fits a promoted category.", "business/boi/")]),
    editorial("business/company-setup", "Thailand Company Setup for Foreigners | Start with the Structure", "COMPANY SETUP", "Build the business before you rush the registration.", "An appropriate company structure starts with what you will actually do. Prepare an activity brief and have the ownership, licences and work permissions reviewed together.",
              [("Write an activity brief", "Include your products or services, customer locations, expected revenue model and your role. A reviewer can then identify the legal and operating questions relevant to your proposal."), ("Prepare an itemised setup scope", "Ask what registration, accounting setup, licences, visa coordination and work-permission support are included. Separate official fees from professional fees and recurring obligations."), ("Plan the first year", "Forecast banking, payroll, accounting, filing and rent alongside the commercial budget. Ask who is responsible for each filing and deadline."), ("Keep the structure lawful", "Do not use nominee shareholders. Have the ownership and control arrangements checked by a qualified Thai lawyer before signing or funding them.")],
              sources=["dbd"], checklist=["Activity and ownership review", "Licensing and work-permission review", "Itemised setup quote", "Accounting and filing calendar"]),
    editorial("business/boi", "Thailand BOI Investment Promotion | Questions for Your Business", "BOI INVESTMENT PROMOTION", "Explore the fit before you count on the benefits.", "Thailand's Board of Investment promotes qualifying activities. The appropriate review begins with your business activity and its evidence.",
              [("Identify a relevant activity category", "Describe the product or service, technology, investment and staffing. Compare the proposal with current BOI categories before building a plan around assumed incentives."), ("Understand the commitments", "Promotion can come with conditions and reporting. Have advisers review the ongoing obligations, ownership and operating permissions associated with the proposed activity."), ("Coordinate the application and the move", "The company, your work role and your personal residence each need an appropriate plan. Ask for a timeline that shows which decision depends on which approval.")], sources=["boi"]),
    editorial("invest", "Invest in Thailand | Property & Business Due Diligence", "INVEST WITH A CLEARER PICTURE", "Understand the decision behind the opportunity.", "A property or business investment deserves careful questions about ownership, costs, documents and the downside, alongside the opportunity.",
              [("Start with your objective", "Are you looking for a home, rental income, a commercial business or a long-term investment? Separate the practical use from the hoped-for return and describe your time horizon."), ("Check independently", "Arrange independent legal, tax and commercial reviews as appropriate. Confirm title, licences, liabilities, ownership conditions and funding evidence for the actual transaction."), ("Model the costs and uncertainty", "Include maintenance, vacancy, management, taxes and transaction costs in your assumptions. Rental income and investment returns are not guaranteed."), ("Decide after the documents", "A compelling presentation is the beginning of a review. Ask for the underlying evidence and contract terms before committing funds.")],
              sources=["condo", "dbd"], cards=[("Condo buying guide", "The checks before a property commitment.", "homes/buy-condo-thailand/"), ("Ownership checklist", "Prepare the right questions for a legal review.", "tools/ownership-checker/")]),
    editorial("living", "Living in Thailand | Relocation, Costs & Settling In", "LIFE AFTER THE FLIGHT", "Make Thailand feel like everyday life.", "The move becomes real in the small things: a home that works, a manageable budget and a clear first-week plan.",
              [("Before you arrive", "Confirm your intended immigration route, accommodation, insurance, document needs and an arrival budget. Keep your plans flexible while applications or travel arrangements remain uncertain."), ("Your first weeks", "Make a practical list for accommodation, phone and internet, transport and the appointments relevant to your situation. Banks and service providers set their own requirements; confirm those before an appointment."), ("Your ongoing calendar", "Record the deadlines and conditions attached to your permission to stay. Your tax circumstances, work activity and insurance need appropriate advice as your situation changes.")],
              image="coast", cards=[("Moving checklist", "A useful plan you can print and bring with you.", "living/moving-checklist/"), ("Cost of living", "Build a budget that reflects how you live.", "living/cost-of-living/"), ("Pattaya neighbourhoods", "A starting point for choosing your first base.", "living/pattaya/")]),
    editorial("living/pattaya", "Living in Pattaya | Choose Your Neighbourhood", "OUR PATTAYA BASE", "Find your kind of Pattaya.", "Pattaya offers different rhythms within a short distance. Choose the neighbourhood around the life you want to lead, then visit at the times you would normally be there.",
              [("Jomtien and Na Jomtien", "Explore these areas if a coastal setting is high on your list. Compare actual access to shops and services, transport, construction nearby and the building's rules before choosing a home."), ("Pratumnak and central Pattaya", "Look at the balance between access to the centre and the setting of each individual street. Check hills, walkability, noise and the journey to the places you will use regularly."), ("Wong Amat and Naklua", "Compare northern neighbourhoods for your housing preferences and routine. Building quality, maintenance and the immediate surroundings matter more than the area name alone."), ("East Pattaya", "If you want more space or are planning around a school, explore the actual commute and transport needs. Factor a vehicle and day-to-day travel into your monthly budget.")],
              checklist=["Visit at morning and evening", "Check your everyday journeys", "Confirm internet and utilities", "Review lease and building rules"]),
    editorial("living/cost-of-living", "Cost of Living in Thailand | Build Your Own Budget", "YOUR THAILAND BUDGET", "Make the numbers fit your life.", "A realistic budget starts with your choices, rather than an internet average. Put rent, food, transport, healthcare and setup costs on the same page.",
              [("Separate monthly and arrival costs", "Rent and groceries repeat. Deposits, flights and initial setup do not. Show both so you understand what you need to arrive and what you need to maintain your routine."), ("Price the choices that matter to you", "A central apartment, a larger family home, dining out, a vehicle and international schooling change the budget. Get actual quotes for your shortlisted home and services."), ("Keep room for changes", "Allow a buffer for exchange-rate movements, travel and unexpected expenses. The calculator uses editable planning assumptions, not a live market quotation."), ("Make the next conversation specific", "Bring your completed budget and explain what matters most. We can help prioritise the housing and relocation questions that would improve the estimate.")],
              image="coast", cards=[("Open the budget calculator", "Change every assumption and see the total update.", "tools/cost-calculator/")]),
    editorial("living/moving-checklist", "Moving to Thailand Checklist | Before Arrival & First Month", "YOUR MOVE, IN ORDER", "Less to remember. More to look forward to.", "Use this practical checklist to organise the move, then adapt it to your visa route, family and current country of residence.",
              [("First: choose the route", "Review your purpose, intended stay and documentary evidence. Check the responsible embassy or authority before committing to travel or non-refundable payments."), ("Before the flight", "Prepare accepted documents, insurance, accommodation and an arrival budget. Confirm current arrival requirements with official sources. Keep copies of the documents you will need."), ("During your first week", "Check the accommodation inventory and lease details. Arrange a phone connection and transport, and confirm the requirements for any bank or government appointment you plan to attend."), ("Before the first month ends", "Record immigration deadlines and relevant address matters. Review your healthcare and work arrangements and seek appropriate tax advice for your circumstances."), ("As your plans develop", "Update the calendar when your status, employment or family situation changes. Keep a record of your application documents and who is handling each next step.")],
              image="coast", sources=["evisa", "immigration"], checklist=["Visa and evidence reviewed", "Insurance and arrival requirements checked", "Accommodation and setup budget prepared", "Deadline calendar created", "First-month priorities agreed"]),
    editorial("residency-care", "Thailand Residency Care | Reporting & Renewal Coordination", "AFTER YOU HAVE SETTLED IN", "Keep living your life. Keep your next steps clear.", "Residency Care helps organise the reminders and coordination relevant to your immigration status. Start with your actual obligations and agree the support you want.",
              [("A calendar for your own status", "Reporting and renewal requirements are not identical for every route. We help organise a calendar around the permission and conditions that apply to you."), ("Renewals with time to prepare", "Agree who gathers the evidence, who coordinates appointments and which deadlines are yours to meet. A reminder does not itself complete an immigration obligation."), ("Travel and changes", "Check the arrangements for travel, a new passport, a change of address or a change in your circumstances before assuming your previous process still applies."), ("A scope you can understand", "Ask for a written annual scope, service fee and any exclusions. Official fees and services outside the agreed scope should be listed separately.")], sources=["immigration", "ltr"]),
    editorial("about", "About Move In Thailand | One Desk for Your Whole Move", "A CALM EXPERT FRIEND", "Big decisions feel better with a clear plan.", "Move In Thailand brings the visa, housing and practical relocation conversations to one desk, with a base in Pattaya and a focus on what you need next.",
              [("Your move is the starting point", "We begin with why you want to come, how you will support yourself and what a good life here looks like to you. The plan should fit your circumstances and the evidence you can provide."), ("The promises we work around", "One coordinated desk. A written fee breakdown before paid work. Appropriate checks before a commitment. Support that connects arrival with the practical steps that follow."), ("Clarity includes saying what needs checking", "Immigration decisions belong to the authorities. Legal structures and transactions need qualified review. We explain what is known, what needs confirming and which adviser should handle the specialist question."), ("Meet the people handling your case", "Ask for the name of your coordinator, the proposed scope and the professional credentials of any specialist before appointing them. You should know who is responsible for each stage.")], image="coast"),
    editorial("services", "Thailand Relocation Services | Visa, Home, Business & Residency", "ONE COORDINATED DESK", "The whole move, considered together.", "Begin with the question that matters most to you. We connect the next steps for visas, housing, business and everyday life into an understandable plan.",
              [("Visa Desk", "Compare the route with your purpose and evidence, then prepare a document and application plan."), ("Homes", "Coordinate a rental or property search around your budget, priorities and arrival timeline."), ("Business and investment", "Prepare your questions for independent legal and commercial review before a commitment."), ("Residency Care", "Organise the relevant deadlines and agree the ongoing coordination you need.")], image="coast"),
    editorial("privacy", "Privacy & Enquiries | Move In Thailand", "YOUR INFORMATION", "Only what we need to start a conversation.", "When you send an enquiry, we ask for contact details and the priorities relevant to your move. Please keep identity documents and detailed financial records out of the initial form.",
              [("What the enquiry form collects", "Your name, email, an optional contact number, selected interest, move timeline, optional budget and your message. We record your permission to contact you, the submission time and the enquiry source. Security checks use a hashed network identifier for short-term rate limiting."), ("Why we use it", "To respond to the enquiry, prepare for your requested conversation and coordinate the services you ask about. Marketing permission is optional and separate from permission to answer your enquiry."), ("Where your enquiry goes", "The enquiry is stored in our WordPress administration system and a notification can be sent to the website's configured administrative email. Access is restricted to authorised staff. We do not collect card details or passport uploads through this form."), ("Your choices", "You can request access, correction, deletion or withdrawal of marketing consent through the contact form. Select privacy request as your subject and provide enough information for us to identify the enquiry. We may need to verify the request before acting."), ("Retention and specialist services", "Initial enquiries have a 180-day retention period in this system unless needed for an ongoing requested service or a legal obligation. Any later identity checks, professional work or third-party sharing need their own explanation and appropriate arrangements."), ("Cookies and tools", "The Visa Finder and cost calculator run in your browser. They do not require an account or contact details. The site does not install new analytics or advertising trackers as part of this rebuild.")], image="coast"),
]

EXTRA_VISA_FAQ = {
    'dtv': [('Does five-year validity mean I can remain for five years without leaving?', 'No. Visa validity and the permission granted for an individual stay are separate. Read the current entry and extension conditions with your responsible authority.'), ('Should I book an activity before checking the evidence?', 'First confirm that the activity and provider documentation meet your embassy’s current requirements. Understand the provider’s cancellation terms before making a payment.'), ('Can my family use my DTV plan?', 'Qualifying spouses and dependants may have a route, with their own evidence. Review the relationship documents and each family member’s intended activity before applying.')],
    'ltr': [('Where should an LTR review begin?', 'With one specific BOI category and the evidence that supports it. Prepare your employment, income, insurance and dependant context as relevant to that category.'), ('Should I arrange investments before a category review?', 'Get a qualified review of the current criteria and your circumstances before moving substantial funds or making an irreversible commitment.'), ('What happens if my circumstances change?', 'Check your continuing qualifications and obligations with the BOI and the relevant authority. A change in employment, income or family circumstances may affect the plan.')],
    'thailand-privilege': [('Where can I verify the current membership price?', 'Use Thailand Privilege’s official programme information and a current written quotation. Compare the tier, term, family arrangements and services you expect to use.'), ('Should I compare membership with a retirement or family route?', 'Yes, if those purposes fit your circumstances. Compare the accepted evidence, total cost, permitted activity and ongoing obligations before deciding.'), ('Does the membership cover every cost of my move?', 'Review the membership’s actual benefits separately from housing, insurance, relocation and other professional costs. Ask which provider and terms apply to each service.')],
    'retirement': [('Which documents should I bring to an initial route review?', 'Your nationality, current residence, intended stay, age and a broad outline of your financial and insurance arrangements. Submit sensitive supporting records only through an agreed secure process.'), ('Can I choose my home before the visa route is clear?', 'You can research neighbourhoods and shortlist rentals. Coordinate deposits, lease dates and non-refundable payments with a checked application and arrival plan.'), ('How do I plan healthcare alongside the move?', 'Review actual cover, exclusions, costs and access to the care you use. Check any visa-specific insurance conditions with the responsible authority and an appropriate insurance professional.')],
    'business': [('Does registering a company solve the visa question?', 'Company registration, permitted business activity, a visa and work permission are separate checks. Describe what you will actually do and have the complete structure reviewed.'), ('What should I check before buying an existing business?', 'Accounts, licences, leases, staff obligations, debts, disputes and the proposed transaction structure. Independent legal and commercial due diligence should come before a deposit.'), ('What makes a useful first business brief?', 'Explain your customers, services, operating location, proposed ownership, budget and personal role. Those details help the appropriate professional identify the right questions.')],
    'marriage': [('Do relationship documents need translation or legalisation?', 'Accepted documents and any translation or legalisation requirements depend on the responsible authority and application. Check that authority’s current checklist for your own civil documents.'), ('Can family members automatically use the same visa?', 'Do not assume one person’s visa covers everyone. Review each relationship, age, purpose and the main applicant’s actual status with the responsible authority.'), ('How should we coordinate the move as a family?', 'Put the visa review, housing, school plans, healthcare and travel dates on the same timeline. Identify the documents and decisions that must happen before a commitment.')],
    'education': [('What should I ask the school or activity provider?', 'Ask about recognition, the actual programme, attendance, supporting documents, total fees and cancellation terms. Confirm accepted visa evidence independently with your responsible embassy.'), ('Is an activity-based DTV the same as an education visa?', 'They are different purposes and processes. Explain the genuine study or activity you intend to undertake and compare the current accepted routes and evidence.'), ('How should a child’s school plan be reviewed?', 'Start with the intended school attendance and the institution’s supporting documents. Review the child’s education route and any parent or guardian arrangements separately.')],
}

from guides import GUIDE_SOURCES, GUIDES, PAGE_UPDATES, VISA_UPDATES

SOURCES.update(GUIDE_SOURCES)
for visa in VISAS:
    update = VISA_UPDATES.get(visa['slug'], {})
    if update.get('sections'):
        visa['sections'] = update['sections']
    visa['faqs'].extend(update.get('faqs', []))
    visa['sources'] += [key for key in update.get('sources', []) if key not in visa['sources']]
    visa['related'] = update.get('related', [])
    visa['next'] = update.get('next')

for visa in VISAS:
    visa['faqs'].extend(EXTRA_VISA_FAQ[visa['slug']])
    PAGES.append(dict(slug=f"visas/{visa['slug']}", title=f"{visa['name']} | Requirements & Planning | Move In Thailand", description=visa["summary"][:155], template="visa", visa=visa))

_by_slug = {page['slug']: page for page in PAGES}
for slug, update in PAGE_UPDATES.items():
    page = _by_slug[slug]
    if update.get('sections'):
        page['sections'] = update['sections']
    page['faqs'] = page.get('faqs', []) + update.get('faqs', [])
    page['sources'] = page.get('sources', []) + [key for key in update.get('sources', []) if key not in page.get('sources', [])]
    known = {card[2] for card in page.get('cards', [])}
    page['cards'] = page.get('cards', []) + [card for card in update.get('cards', []) if card[2] not in known]
    page['related'] = update.get('related', [])
    page['next'] = update.get('next')
for guide in GUIDES:
    if guide.get('checklist'):
        guide.setdefault('checklist_title', 'Key facts at a glance.')
PAGES.extend(GUIDES)

for page in PAGES:
    page.setdefault("heading", page["title"].split(" | ")[0])
    page.setdefault("faqs", [])
    page.setdefault("sources", [])
    for key, empty in (("related", []), ("next", None), ("short", ""), ("checklist_title", ""), ("cards", []), ("checklist", [])):
        page.setdefault(key, empty)

CALCULATOR_DEFAULTS = {
    "rent": 22000, "food": 12000, "transport": 3500,
    "health": 5000, "utilities": 3000, "personal": 4500,
    "deposit": 44000, "setup": 20000, "buffer": 15,
}

# Home page route comparison. Figures match the visa guides; "years" drives the bar
# (permission per approval, on a 20-year scale) and is shown next to it in words.
ROUTE_SPECS = [
    dict(slug='dtv', short='DTV', name='Destination Thailand Visa', years=5, length='5-year visa, up to 180 days per entry',
         suits='Remote workers, and Muay Thai, cooking or culture students', money='500,000 THB in savings', work='Only for employers or clients abroad'),
    dict(slug='ltr', short='LTR', name='Long-Term Resident', years=10, length='Up to 10 years',
         suits='High earners, pensioners, investors and skilled professionals', money='Income, assets or employer criteria by category', work='Depends on the category'),
    dict(slug='thailand-privilege', short='Privilege', name='Thailand Privilege', years=20, length='5 to 20 years, by membership tier',
         suits='People who would rather pay than prove an income', money='A one-off membership fee', work='Not from membership alone'),
    dict(slug='retirement', short='Retirement', name='Retirement visa', years=1, length='1 year at a time, renewed yearly',
         suits='Anyone aged 50 or over', money='800,000 THB in a Thai bank, or 65,000 THB a month', work='No'),
]
